### ISSUE TITLE
Similarity

### ISSUE THREAD

**Issue by celalnuriakgun** [madmath03/pmadarktheme#2]
This theme is not exactly the same, but it is successful. Can you do exactly the same?

**Comment by madmath03** [comment]
Is the similar theme you're talking about [mjohnson8165/pma8165-theme](https://github.com/mjohnson8165/pma8165-theme)? If that's the case, it should already be identical, apart from the bug fixes, charts and relation view already mentioned in the `README`.

can you give me some examples of what you think is not the same?

**Comment by celalnuriakgun** [comment]
Your design:

![ekran alintisi](https://user-images.githubusercontent.com/14141670/37966328-d211eac2-31d0-11e8-9495-a0a961d1290f.PNG)

PMA8165 design:

![](https://raw.githubusercontent.com/mjohnson8165/pma8165-theme/master/screenshot-2.png)

**Comment by madmath03** [comment]
I'm sorry but I do not understand what you mean. You simply shared a screenshot of the whole application without specifying where to look... 

The only differences I see, and my thoughts about them:
- the **icons** : this comes from using `pmahomme` as the base but I think they were meant to be there in the original theme, otherwise, why would mjohnson8165 bother creating the black and white icons in the first place.
- the **size** : the original theme is slightly wider and the difference, again, comes from the choice I made of using `pmahomme` as the base.
In both cases, I actually think those aspects make the theme easier to read than the original version.

This theme is a fork inspired by PMA8165 but, as mentioned in the doc, with a different base material.
Unless you provide me with some actual bugs, I will close this issue.

**Comment by celalnuriakgun** [comment]
OK, thank you so much anyway.
